//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  tratamiento: Tratamiento;
  tratamientoConnection: TratamientoConnection;
  doctora: Doctora;
  doctoraConnection: DoctoraConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTratamientoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTratamientoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TratamientoFilter>;
};


export type QueryDoctoraArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDoctoraConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DoctoraFilter>;
};

export type DocumentFilter = {
  tratamiento?: InputMaybe<TratamientoFilter>;
  doctora?: InputMaybe<DoctoraFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Tratamiento | Doctora | Folder;

export type Tratamiento = Node & Document & {
  __typename?: 'Tratamiento';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TratamientoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type TratamientoConnectionEdges = {
  __typename?: 'TratamientoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tratamiento>;
};

export type TratamientoConnection = Connection & {
  __typename?: 'TratamientoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TratamientoConnectionEdges>>>;
};

export type Doctora = Node & Document & {
  __typename?: 'Doctora';
  name: Scalars['String']['output'];
  specialty?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DoctoraFilter = {
  name?: InputMaybe<StringFilter>;
  specialty?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
};

export type DoctoraConnectionEdges = {
  __typename?: 'DoctoraConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Doctora>;
};

export type DoctoraConnection = Connection & {
  __typename?: 'DoctoraConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DoctoraConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateTratamiento: Tratamiento;
  createTratamiento: Tratamiento;
  updateDoctora: Doctora;
  createDoctora: Doctora;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateTratamientoArgs = {
  relativePath: Scalars['String']['input'];
  params: TratamientoMutation;
};


export type MutationCreateTratamientoArgs = {
  relativePath: Scalars['String']['input'];
  params: TratamientoMutation;
};


export type MutationUpdateDoctoraArgs = {
  relativePath: Scalars['String']['input'];
  params: DoctoraMutation;
};


export type MutationCreateDoctoraArgs = {
  relativePath: Scalars['String']['input'];
  params: DoctoraMutation;
};

export type DocumentUpdateMutation = {
  tratamiento?: InputMaybe<TratamientoMutation>;
  doctora?: InputMaybe<DoctoraMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  tratamiento?: InputMaybe<TratamientoMutation>;
  doctora?: InputMaybe<DoctoraMutation>;
};

export type TratamientoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type DoctoraMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  specialty?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
};

export type TratamientoPartsFragment = { __typename: 'Tratamiento', title: string, description?: string | null, icon?: string | null };

export type DoctoraPartsFragment = { __typename: 'Doctora', name: string, specialty?: string | null, image?: string | null, bio?: string | null, location?: string | null };

export type TratamientoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TratamientoQuery = { __typename?: 'Query', tratamiento: { __typename: 'Tratamiento', id: string, title: string, description?: string | null, icon?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TratamientoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TratamientoFilter>;
}>;


export type TratamientoConnectionQuery = { __typename?: 'Query', tratamientoConnection: { __typename?: 'TratamientoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TratamientoConnectionEdges', cursor: string, node?: { __typename: 'Tratamiento', id: string, title: string, description?: string | null, icon?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DoctoraQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DoctoraQuery = { __typename?: 'Query', doctora: { __typename: 'Doctora', id: string, name: string, specialty?: string | null, image?: string | null, bio?: string | null, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DoctoraConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DoctoraFilter>;
}>;


export type DoctoraConnectionQuery = { __typename?: 'Query', doctoraConnection: { __typename?: 'DoctoraConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DoctoraConnectionEdges', cursor: string, node?: { __typename: 'Doctora', id: string, name: string, specialty?: string | null, image?: string | null, bio?: string | null, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const TratamientoPartsFragmentDoc = gql`
    fragment TratamientoParts on Tratamiento {
  __typename
  title
  description
  icon
}
    `;
export const DoctoraPartsFragmentDoc = gql`
    fragment DoctoraParts on Doctora {
  __typename
  name
  specialty
  image
  bio
  location
}
    `;
export const TratamientoDocument = gql`
    query tratamiento($relativePath: String!) {
  tratamiento(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TratamientoParts
  }
}
    ${TratamientoPartsFragmentDoc}`;
export const TratamientoConnectionDocument = gql`
    query tratamientoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TratamientoFilter) {
  tratamientoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TratamientoParts
      }
    }
  }
}
    ${TratamientoPartsFragmentDoc}`;
export const DoctoraDocument = gql`
    query doctora($relativePath: String!) {
  doctora(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DoctoraParts
  }
}
    ${DoctoraPartsFragmentDoc}`;
export const DoctoraConnectionDocument = gql`
    query doctoraConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DoctoraFilter) {
  doctoraConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DoctoraParts
      }
    }
  }
}
    ${DoctoraPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      tratamiento(variables: TratamientoQueryVariables, options?: C): Promise<{data: TratamientoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TratamientoQueryVariables, query: string}> {
        return requester<{data: TratamientoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TratamientoQueryVariables, query: string}, TratamientoQueryVariables>(TratamientoDocument, variables, options);
      },
    tratamientoConnection(variables?: TratamientoConnectionQueryVariables, options?: C): Promise<{data: TratamientoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TratamientoConnectionQueryVariables, query: string}> {
        return requester<{data: TratamientoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TratamientoConnectionQueryVariables, query: string}, TratamientoConnectionQueryVariables>(TratamientoConnectionDocument, variables, options);
      },
    doctora(variables: DoctoraQueryVariables, options?: C): Promise<{data: DoctoraQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DoctoraQueryVariables, query: string}> {
        return requester<{data: DoctoraQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DoctoraQueryVariables, query: string}, DoctoraQueryVariables>(DoctoraDocument, variables, options);
      },
    doctoraConnection(variables?: DoctoraConnectionQueryVariables, options?: C): Promise<{data: DoctoraConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DoctoraConnectionQueryVariables, query: string}> {
        return requester<{data: DoctoraConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DoctoraConnectionQueryVariables, query: string}, DoctoraConnectionQueryVariables>(DoctoraConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  